version: '3.5'

services:
  postgres-account:
    image: postgres
    container_name: acme-pay-notification-service
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notification-service
    volumes:
      - "./data/accounts/postgres:/var/lib/postgres/data"
    ports:
      - 5435:5432